footprint: [[0.506, 0.315], [0.506, -0.315], [-0.506, -0.315], [-0.506, 0.315]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 4.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 2.0
raytrace_range: 2.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan_multi, marking: true, clearing: true}

inflation:
  inflation_radius: 0.5