global_costmap:
  global_frame: map
  static_map: true

  plugins:
  - {name: static,      type: "costmap_2d::StaticLayer"}
  - {name: obstacles,       type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}