# https://answers.ros.org/question/397359/ - FOllow this guidelines for omni ?
amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "kmriiwa_base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: 0.15
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "kmriiwa_odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1
    resample_interval: 1
    robot_model_type: "nav2_amcl::OmniMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: "/scan_multi"

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: kmriiwa_base_footprint
    odom_frame: kmriiwa_odom
    bt_loop_duration: 10
    default_server_timeout: 20
    default_nav_through_poses_bt_xml: /opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
    default_nav_to_pose_bt_xml: /opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0 # Previously was 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2 #0.5
      movement_time_allowance: 15.0 #10.0

    # Goal checker parameters
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05 #0.25
      yaw_goal_tolerance: 0.05 #0.25
      stateful: true

    # DWB parameters
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      model_dt: 0.05 # Delete this when not using mppi
      debug_trajectory_details: True
      min_vel_x: -0.1 # Previously -0.26
      vx_min: -0.2 # MPPI stuff
      min_vel_y: -0.1 # Seems to not work, even though omni
      vy_min: -0.1
      max_vel_x: 0.1 # Previously 0.26
      vx_max: 0.2 # MPPI stuff
      max_vel_y: 0.1 # Seems to not work, even though omni
      vy_max: 0.1 # MPPI stuff
      max_vel_theta: 0.2 # Previously 1.0 - Very good speed but trip in emergency
      wz_max: 0.5 # MPPI stuff
      min_speed_xy: -0.15 # Preopvilsy 0.0, seeing if this performs good, Really shit with -0.26, setting it to 0.0
      max_speed_xy: 0.15 # Really shit with 0.26
      min_speed_theta: 0.0
      ax_max: 1.5
      ax_min: -1.5
      ay_max: 1.5
      az_max: 1.5
      acc_lim_x: 0.3
      acc_lim_y: 0.3 # Acceleration previously set to 0.0, seeing if it works for omni- y direction
      acc_lim_theta: 0.3 # Previiuksy 3.2
      decel_lim_x: -0.5 #-2.5
      decel_lim_y: -0.5 #-2.5
      decel_lim_theta: -0.5#-3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["ConstraintCritic", "CostCritic", "GoalAngleCritic", "GoalCritic", "ObstaclesCritic", "PathAlignCritic", "PathFollowCritic", "PreferForwardCritic"] # Removed "RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"
      # BaseObstacle.scale: 0.02 - very close to obstacle
      BaseObstacle.scale: 0.05
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    transform_tolerance: 1.0
    tf_buffer_duration: 15.0
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.1 #0.5
      use_astar: true
      allow_unknown: true

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: kmriiwa_odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: false
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

local_costmap:
  local_costmap:
    ros__parameters:
      transform_tolerance: 1.0
      tf_buffer_duration: 15.0
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: kmriiwa_odom
      robot_base_frame: kmriiwa_base_footprint
      use_sim_time: false
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      #robot_radius: 0.22 # KMRIIWA not round base , but polygon chaning this
      footprint: "[[0.60,0.375],[0.60,-0.375],[-0.60,-0.375],[-0.60,0.375]]"
      clearing_rotation_allowed: true
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        #inflation_radius: 0.55 # Kept default
        inflation_radius: 0.05 #0.55
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan_merged
        scan_merged:
          topic: /scan_multi
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      transform_tolerance: 1.0
      tf_buffer_duration: 15.0
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: kmriiwa_base_footprint
      use_sim_time: false
      #robot_radius: 0.22
      footprint: "[[0.60,0.375],[0.60,-0.375],[-0.60,-0.375],[-0.60,0.375]]"
      #footprint: "[[0.60,0.355],[0.60,-0.355],[-0.60,-0.355],[-0.60,0.355]]" - Too close
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan_merged
        scan_merged:
          topic: /scan_multi
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        #inflation_radius: 0.55 # Kept default value
        inflation_radius: 0.20
      always_send_full_costmap: True
rviz:
  ros__parameters:
    use_sim_time: false
    tf_buffer_duration: 30.0
    message_filters_queue_size: 200

/tf:
  ros__parameters:
    message_filters_queue_size: 200
