controller_list:
  - name: fake_manipulator_controller
    joints:
      - kmriiwa_joint_1
      - kmriiwa_joint_2
      - kmriiwa_joint_3
      - kmriiwa_joint_4
      - kmriiwa_joint_5
      - kmriiwa_joint_6
      - kmriiwa_joint_7
  - name: fake_endeffector_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: manipulator
    pose: home